# Generated by Django 2.1.5 on 2019-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximity', '0002_auto_20190320_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('interest', models.TextField()),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='username',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
